config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  get 'API/:devel_id/users/:user_ext_id/posts' => 'api_user#get_posts', as: :api_get_user_posts
  get 'API/:devel_id/users/:user_ext_id/following' => 'api_user#get_following', as: :api_get_user_following
  get 'API/:devel_id/users/:user_ext_id/followers' => 'api_user#get_followers', as: :api_get_user_followers
  

  resources :users do
    member do
      get 'follower_posts'
    end
    resources :posts
  end

  get 'users/:user_id/follow/:friend_id' => 'users#follow', as: :follow_user
  get 'users/:user_id/unfollow/:friend_id' => 'users#unfollow', as: :unfollow_user

  
end

app/models/friendship.rb
class Friendship < ActiveRecord::Base
    
  belongs_to :user
  belongs_to :friend, :class_name => 'User'

  validate :different_users
  
  def different_users
    if user_id == friend_id
      errors.add(:same_user, "user cannot follow himself")
    end
  end
  
end

app/models/post.rb
class Post < ActiveRecord::Base

  belongs_to :user
  
  validates :text, length: { maximum: 160 }

end

app/models/user.rb
#require 'bcrypt'

class User < ActiveRecord::Base
  has_secure_password

  has_many :posts
  has_many :friendships
  # followings
  has_many :followings, :through => :friendships,
                        :source  => :friend
  has_many :inverse_friendships, :class_name  => 'Friendship',
                                 :foreign_key => 'friend_id'
  # followers
  has_many :followers, :through => :inverse_friendships,
                       :source  => :user

  before_save :hash_new_password, :if => :password_changed?
  
  validates :email, :nick, presence: true
  validates :nick, uniqueness: true
  validates :password, presence: true, on: :create
  validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
  
  # By default the form_helpers will set the new_pass to "",
  # we don't want to go saving this as a password
  def password_changed?
    !@new_pass.blank?
  end
  
  # list of available users to follow
  def to_follow
    followers_and_user = self.followings + [self]
    User.where.not(id: followers_and_user)
  end
  
  private
  # We need to encrypt the user password before saving
  def hash_new_password
    self.password = BCrypt::Password.create(@password)
  end
end

app/controllers/api_user_controller.rb
class ApiUserController < ApplicationController

  before_action :check_devel_id, only: [:get_post, :get_following, :get_followers]

  def get_posts
    user = User.find(translate_external_user_id(params[:user_ext_id]))
    @posts = user.posts
    render json: @posts
  end

  def get_following
    user = User.find(translate_external_user_id(params[:user_ext_id]))
    @followings = user.followings
    render json: @followings
  end

  def get_followers
    user = User.find(translate_external_user_id(params[:user_ext_id]))
    @followers = user.followers
    render json: @followers
  end

  private
  # method to translate the external id to the internal one (in this
  # case, it doesn't do anything)
  def translate_external_user_id(ext_id)
    ext_id
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  #filter_parameter_logging :password
  
  # method to check the devel_id parameter received from a external API call
  def check_devel_id
    true  
  end
  
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    
  def create
    @user = User.find(params[:user_id])
    @post = @user.posts.create(post_params)
    redirect_to user_path(@user)
  end
  
  private
  def post_params
    params.require(:post).permit(:text)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end
    
  def new
    @user = User.new
  end
  
  def create
    # render plain: params[:user].inspect
    @user = User.new(user_params)
    
    if @user.save
      redirect_to @user
    else
      render 'new'
    end
  end
  
  def update
    @user = User.find(params[:id])
    
    if @user.update(user_params)
      redirect_to @user
    else
      render 'edit'
    end
  end
  
  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end
  
  def destroy
    @user = User.find(params[:id])
    @user.destroy
    
    redirect_to users_path
  end

  # Adding a new following user
  def follow
    @user = User.find(params[:user_id])
    friend = User.find(params[:friend_id])
    if !@user.blank? and !friend.blank?
      Friendship.create(:user => @user, :friend => friend)
    end
    render 'show'
  end

  # Removing following user
  def unfollow
    @user = User.find(params[:user_id])
    Friendship.where(user:   @user,
                     friend: params[:friend_id]).destroy_all
    render 'show'
  end
  
  def follower_posts
    @user = User.find(params[:id])
    @posts = Post.where(user_id: @user.followings)
  end
  
  private
  def user_params
    params.require(:user).permit(:email, :nick,
                                 :password, :password_confirmation)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/api_user_helper.rb
module ApiUserHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/api_user/get_followers.html.erb
<h1>ApiUser#get_followers</h1>
<p>Find me in app/views/api_user/get_followers.html.erb</p>

app/views/api_user/get_following.html.erb
<h1>ApiUser#get_following</h1>
<p>Find me in app/views/api_user/get_following.html.erb</p>

app/views/api_user/get_post.html.erb
<h1>ApiUser#get_post</h1>
<p>Find me in app/views/api_user/get_post.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/posts/_form.html.erb
<%= form_for([@user, @user.posts.build]) do |f| %>
  <p>
    <%= f.label :text %>
    <%= f.text_field :text %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/posts/_post.html.erb
<tr>
  <td><%= post.text %></td>
  <td><%= post.created_at %></td>
</tr>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>

  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@user.errors.count, "error") %> prohibited
        this user from being saved:
      </h2>
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
  <p>
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </p>
  
  <p>
    <%= f.label :nick %><br>
    <%= f.text_field :nick %>
  </p>
  
  <p>
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </p>
  
  <p>
    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation %>
  </p>
  
  <p>
    <%= f.submit %>
  </p>
  
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/follower_posts.html.erb
<h1>Follower Posts for user <%= @user.id %></h1>

<% unless @posts.empty? %>
  <h2>Posts</h2>
  <table>
    <tr>
      <th>Text</th>
      <th>Time</th>
    </tr>
    <%= render @posts %>
  </table>
<% end %>

<%= link_to 'Back', user_path(@user) %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<%= link_to 'New User', new_user_path %>

<table>
  <tr>
    <th>Nick</th>
    <th>Email</th>
    <th colspan="3"></th>
  </tr>
  
  <% @users.each do |user| %>
    <tr>
      <td><%= user.nick %></td>
      <td><%= user.email %></td>
      <td><%= link_to 'Show', user_path(user) %></td>
      <td><%= link_to 'Edit', edit_user_path(user) %></td>
      <td><%= link_to 'Destroy', user_path(user),
                      method: :delete,
                      data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<h1>Show User <%= @user.id %></h1>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>
  
<p>
  <strong>Nick:</strong>
  <%= @user.nick %>
</p>

<% unless @user.posts.empty? %>
  <h2>Posts</h2>
  <table>
    <tr>
      <th>Text</th>
      <th>Time</th>
    </tr>
    <%= render @user.posts %>
  </table>
<% end %>

<h2>Add a new post:</h2>
<%= render 'posts/form' %>

<% unless @user.followers.empty? %>
  <h2>Followers</h2>
  <% @user.followers.each do |follower| %>
    <%= follower.nick %>
  <% end %>
<% end %>

<% unless @user.followings.empty? %>
  <h2>Following users</h2>
  <% @user.followings.each do |following| %>
    <%= link_to following.nick, unfollow_user_path(:user_id => @user.id,
                                                   :friend_id => following.id) %>
  <% end %>
  <%= link_to 'See their posts', follower_posts_user_path(@user) %>
<% end %>

<% unless @user.to_follow.empty? %>
  <h2>Follow a new user</h2>
  <% @user.to_follow.each do |user| %>
    <%= link_to user.nick, follow_user_path(:user_id   => @user.id,
                                            :friend_id => user.id) %>
  <% end %>
<% end %>

<br/><br/><br/>
<%= link_to 'Back', users_path %>
<%= link_to 'Edit', edit_user_path(@user) %>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>